use_frameworks!

target 'MFTAdaptiveTabBarController_Example' do
  pod 'MFTAdaptiveTabBarController', :path => '../'

  target 'MFTAdaptiveTabBarController_Tests' do
    inherit! :search_paths

    
  end
end
