use_frameworks!

platform :ios, '11.4'

target 'AdaptiveTabBarController_Example' do
  pod 'AdaptiveTabBarController', :path => '../'

  target 'AdaptiveTabBarController_Tests' do
    inherit! :search_paths

    
  end
end
